name: Build Android APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b

      - name: Install Gomobile Tool
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          gomobile init

      - name: Compile Go Core to AAR
        run: |
          cd core
          go mod tidy
          mkdir -p ../android/app/libs
          gomobile bind -v -androidapi 21 -target=android/arm64 -o ../android/app/libs/core.aar

      - name: Build Android APK
        run: |
          cd android
          # 如果没有现成的 gradlew，自动生成一个
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FirefoxVPN-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk
